# Generated by Django 3.2.25 on 2025-11-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
                ('summary', models.TextField()),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
